/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andulanarobert1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;

/**
 *
 * @author student
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProduct_id = new javax.swing.JTextField();
        jProduct_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jBarcode = new javax.swing.JTextField();
        jUnit_price = new javax.swing.JTextField();
        jSelling_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pComboBox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jDescription = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jQuantity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        uComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jReorder = new javax.swing.JTextField();
        InsertBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCost_price1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSupplier1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jProduct_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 250, -1));

        jProduct_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProduct_nameActionPerformed(evt);
            }
        });
        getContentPane().add(jProduct_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 250, -1));

        jLabel1.setText("Description");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel3.setText("Product Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel4.setText("Product Category");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 470, 10));
        getContentPane().add(jBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 250, 40));

        jUnit_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnit_priceActionPerformed(evt);
            }
        });
        getContentPane().add(jUnit_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 110, -1));

        jSelling_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelling_priceActionPerformed(evt);
            }
        });
        getContentPane().add(jSelling_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 110, -1));

        jLabel5.setText("Product Status");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));

        jLabel6.setText("Unit Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        jLabel7.setText("Selling Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, -1));

        jLabel8.setText("Quantity in Stock");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, -1));
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        pComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Drink", "Equipment" }));
        pComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(pComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jDescription.setColumns(20);
        jDescription.setRows(5);
        jScrollPane4.setViewportView(jDescription);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 250, 110));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Swis721 BT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Product");

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grocery-store (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 590, 60));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 10, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Pricing & Inventory");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jLabel10.setText("Product ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("️ Product Information");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));
        getContentPane().add(jQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 110, -1));

        jLabel12.setText("Barcode");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

        sComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        getContentPane().add(sComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        jLabel13.setText("Unit of Measure");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        uComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pcs", "box", "kg", "liter" }));
        getContentPane().add(uComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jLabel14.setText("Recorder Level");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        jReorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReorderActionPerformed(evt);
            }
        });
        getContentPane().add(jReorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 110, -1));

        InsertBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        InsertBtn.setText("Add Product");
        InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtnActionPerformed(evt);
            }
        });
        getContentPane().add(InsertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, 120, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 670, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 670, -1, -1));

        jCost_price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCost_price1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCost_price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 110, -1));

        jLabel16.setText("Cost Price");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        jSupplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSupplier1ActionPerformed(evt);
            }
        });
        getContentPane().add(jSupplier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 250, -1));

        jLabel17.setText("Supplier Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSelling_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelling_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSelling_priceActionPerformed

    private void jProduct_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProduct_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProduct_nameActionPerformed

    private void pComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pComboBoxActionPerformed

    private void InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBtnActionPerformed
        // TODO add your handling code here:
        Connection con = DatabaseConnection.dbConnection();
            int pID = Integer.parseInt(jProduct_id.getText());
            String productName = jProduct_name.getText();
            String category = pComboBox.getSelectedItem().toString();
            String description = jDescription.getText();

            int unitPrice = Integer.parseInt(jUnit_price.getText());
            int CostPrice = Integer.parseInt(jCost_price1.getText());
            int sellingPrice = Integer.parseInt(jSelling_price.getText());

            int quantity = Integer.parseInt(jQuantity.getText());
            int reorderLevel = Integer.parseInt(jReorder.getText());

            String unitOfMeasure = uComboBox.getSelectedItem().toString();
            String status = sComboBox.getSelectedItem().toString();
            String supplier_name = jSupplier1.getText();
            String barcode = jBarcode.getText();

         
            try{
                 PreparedStatement pst = con.prepareStatement(
    "INSERT INTO products (product_id, product_name, category_name, description, unit_price, cost_price, selling_price, stock_quantity, reorder_level, unit_of_measure, status, supplier_name, barcode) "
  + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
);
                pst.setInt(1, pID);
                pst.setString(2, productName);
                pst.setString(3, category);
                pst.setString(4, description);
                pst.setInt(5, unitPrice);
                pst.setInt(6, CostPrice);
                pst.setInt(7, sellingPrice);
                pst.setInt(8, quantity);
                pst.setInt(9, reorderLevel);
                pst.setString(10, unitOfMeasure);
                pst.setString(11, status);
                pst.setString(12, supplier_name);
                pst.setString(13, barcode);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data added successfully");
            }
            catch(Exception ex){
                System.out.println(ex);
            } 
            
    }//GEN-LAST:event_InsertBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         jProduct_id.setText("");
    jProduct_name.setText("");
    jDescription.setText("");
    jUnit_price.setText("");
    jSelling_price.setText("");
    jQuantity.setText("");
    jReorder.setText("");
    jBarcode.setText("");
    pComboBox.setSelectedItem(0);
uComboBox.setSelectedItem(0);
sComboBox.setSelectedItem(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showConfirmDialog(null, "Return to Dashboard", "Are you sure?",JOptionPane.YES_NO_OPTION);
        if(confirm == YES_OPTION){
         Dashboard db = new  Dashboard();
        db.show();
        this.dispose();
        }else{
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jUnit_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnit_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUnit_priceActionPerformed

    private void jReorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jReorderActionPerformed

    private void jCost_price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCost_price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCost_price1ActionPerformed

    private void jSupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSupplier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSupplier1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
   
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertBtn;
    private javax.swing.JTextField jBarcode;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jCost_price1;
    private javax.swing.JTextArea jDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jProduct_id;
    private javax.swing.JTextField jProduct_name;
    private javax.swing.JTextField jQuantity;
    private javax.swing.JTextField jReorder;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jSelling_price;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jSupplier1;
    private javax.swing.JTextField jUnit_price;
    private javax.swing.JComboBox<String> pComboBox;
    private javax.swing.JComboBox<String> sComboBox;
    private javax.swing.JComboBox<String> uComboBox;
    // End of variables declaration//GEN-END:variables
}
