/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andulanarobert1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;

/**
 *
 * @author rpand
 */
public class Categories extends javax.swing.JFrame {

    /**
     * Creates new form Categories
     */
    public Categories() {
        initComponents();
        jcattable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = jcattable.getSelectedRow();
                if (selectedRow >= 0) {
                    jcatfield.setText(jcattable.getValueAt(selectedRow, 0).toString());
                    jtadesc.setText(jcattable.getValueAt(selectedRow, 1).toString());
                }
            }
        });
       
            
    }
    
    private void clearFields() {
    jcatfield.setText("");
    jtadesc.setText("");
}
    

    
private void loadCategoryTable() {
    Connection con = DatabaseConnection.dbConnection();
    DefaultTableModel dtm = (DefaultTableModel) jcattable.getModel();
    dtm.setRowCount(0); // clear table

    try {
        String sql = "SELECT category_name, description FROM categories ORDER BY category_name ASC";
        ResultSet rs = con.prepareStatement(sql).executeQuery();

        while (rs.next()) {
            Object[] obj = {
                rs.getString("category_name"),
                rs.getString("description")
            };
            dtm.addRow(obj);
        }
    } catch (Exception ex) {
        System.out.println(ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jcattable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtadesc = new javax.swing.JTextArea();
        jcatupdate = new javax.swing.JButton();
        jdeletecat = new javax.swing.JButton();
        jsearchcat = new javax.swing.JTextField();
        jcatsearchbutton = new javax.swing.JButton();
        jcatfield = new javax.swing.JTextField();
        jcatcreate = new javax.swing.JButton();
        jcatclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Swis721 BT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Categories");

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rpand\\Documents\\GitHub\\Andulana_EDP\\src\\andulanarobert1\\images\\return.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23))))
        );

        jcattable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category", "Description", "Date added"
            }
        ));
        jScrollPane1.setViewportView(jcattable);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Swis721 BT", 3, 18)); // NOI18N
        jLabel3.setText("Category Name");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Swis721 BT", 3, 18)); // NOI18N
        jLabel4.setText("Description");

        jtadesc.setColumns(20);
        jtadesc.setRows(5);
        jScrollPane2.setViewportView(jtadesc);

        jcatupdate.setText("Update");
        jcatupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcatupdateActionPerformed(evt);
            }
        });

        jdeletecat.setText("Delete");
        jdeletecat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeletecatActionPerformed(evt);
            }
        });

        jsearchcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchcatActionPerformed(evt);
            }
        });

        jcatsearchbutton.setText("Search");
        jcatsearchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcatsearchbuttonActionPerformed(evt);
            }
        });

        jcatcreate.setText("Create");
        jcatcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcatcreateActionPerformed(evt);
            }
        });

        jcatclear.setText("Clear");
        jcatclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcatclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(jdeletecat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jcatupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jsearchcat, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcatsearchbutton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcatclear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcatcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jcatfield, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcatsearchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsearchcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jcatfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcatcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcatclear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdeletecat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcatupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jsearchcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchcatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsearchcatActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
     loadCategoryTable();
      
    }//GEN-LAST:event_formWindowActivated

    private void jcatsearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcatsearchbuttonActionPerformed
        // TODO add your handling code here:
           String search = jsearchcat.getText().trim();

    Connection con = DatabaseConnection.dbConnection();
    DefaultTableModel dtm = (DefaultTableModel) jcattable.getModel();
    dtm.setRowCount(0);

    try {
        String sql = "SELECT category_name, description, date_added " +
                     "FROM categories " +
                     "WHERE category_name LIKE ? OR description LIKE ? " +
                     "ORDER BY category_name ASC";

        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, "%" + search + "%");
        pst.setString(2, "%" + search + "%");

        ResultSet rs = pst.executeQuery();
        boolean found = false;

        while (rs.next()) {
            found = true;

            Object obj[] = {
                rs.getString("category_name"),
                rs.getString("description"),
                rs.getString("date_added")
            };

            dtm.addRow(obj);
        }

        if (!found) {
            JOptionPane.showMessageDialog(null, "No matching category found.");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error searching categories: " + ex.getMessage());
    }

    }//GEN-LAST:event_jcatsearchbuttonActionPerformed

    private void jcatupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcatupdateActionPerformed
        // TODO add your handling code here:
      int selectedRow = jcattable.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a category first.");
        return;
    }

    String oldName = jcattable.getValueAt(selectedRow, 0).toString();
    String newName = jcatfield.getText().trim();
    String description = jtadesc.getText().trim();

    if (newName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Category name cannot be empty.");
        return;
    }

    try {
        Connection con = DatabaseConnection.dbConnection();

        String sql = "UPDATE categories SET category_name=?, description=? WHERE category_name=?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, newName);
        pst.setString(2, description);
        pst.setString(3, oldName);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Category updated successfully.");

        clearFields();
        loadCategoryTable();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }//GEN-LAST:event_jcatupdateActionPerformed

    private void jdeletecatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeletecatActionPerformed
        // TODO add your handling code here:
        int selectedRow = jcattable.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a category first.");
        return;
    }

    String categoryName = jcattable.getValueAt(selectedRow, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(this,
            "Delete '" + categoryName + "'?",
            "Confirm", JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) return;

    try {
        Connection con = DatabaseConnection.dbConnection();

        // ✅ Check if products are linked first
        String checkSQL = "SELECT COUNT(*) FROM products p " +
                          "JOIN categories c ON p.category_id = c.category_id " +
                          "WHERE c.category_name = ?";
        PreparedStatement checkStmt = con.prepareStatement(checkSQL);
        checkStmt.setString(1, categoryName);
        ResultSet rs = checkStmt.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this,
                "Cannot delete! This category has " + rs.getInt(1) + " product(s) linked to it.\n" +
                "Please reassign or delete those products first.",
                "Delete Failed", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ✅ Safe to delete
        PreparedStatement pst = con.prepareStatement(
            "DELETE FROM categories WHERE category_name=?");
        pst.setString(1, categoryName);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Category deleted successfully.");
        loadCategoryTable();
        clearFields();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    
    }//GEN-LAST:event_jdeletecatActionPerformed

    private void jcatcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcatcreateActionPerformed
        // TODO add your handling code here:
        String categoryName = jcatfield.getText().trim();
        String description = jtadesc.getText().trim();

        if (categoryName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Category name cannot be empty.");
            return;
        }

        try {
            Connection con = DatabaseConnection.dbConnection();
            String checkSql = "SELECT category_id FROM categories WHERE category_name = ?";
            PreparedStatement pstCheck = con.prepareStatement(checkSql);
            pstCheck.setString(1, categoryName);
            ResultSet rsCheck = pstCheck.executeQuery();

            if (rsCheck.next()) {
                JOptionPane.showMessageDialog(this, "Category already exists.");
                return;
            }

            String insertSql = "INSERT INTO categories (category_name, description) VALUES (?, ?)";
            PreparedStatement pstInsert = con.prepareStatement(insertSql);
            pstInsert.setString(1, categoryName);
            pstInsert.setString(2, description);
            pstInsert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Category created successfully!");
            clearFields();
            loadCategoryTable();
            clearFields();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jcatcreateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           int confirm = JOptionPane.showConfirmDialog(null, "Return to Dashboard", 
        "Are you sure?", JOptionPane.YES_NO_OPTION);
    if (confirm == YES_OPTION) {
        Dashboard db = new Dashboard();
        db.setVisible(true);    // ✅
        this.setVisible(false); // ✅ not dispose()
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcatclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcatclearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_jcatclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jcatclear;
    private javax.swing.JButton jcatcreate;
    private javax.swing.JTextField jcatfield;
    private javax.swing.JButton jcatsearchbutton;
    private javax.swing.JTable jcattable;
    private javax.swing.JButton jcatupdate;
    private javax.swing.JButton jdeletecat;
    private javax.swing.JTextField jsearchcat;
    private javax.swing.JTextArea jtadesc;
    // End of variables declaration//GEN-END:variables
}
