/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andulanarobert1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;


/**
 *
 * @author rpand
 */
public class Suppliers extends javax.swing.JFrame {
private int selectedSupplierId = -1; 
    /**
     * Creates new form Suppliers
     */
    public Suppliers() {
        initComponents();
        jsupid.setEditable(false);
jsupid.setFocusable(false);

jsupcn.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume();
            }
            if (jsupcn.getText().length() >= 11) {
                evt.consume();
            }
        }
    });

    jsupcn.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            String cn = jsupcn.getText().trim();
            if (!cn.isEmpty() && cn.length() != 11) {
                JOptionPane.showMessageDialog(null,
                    "Contact number must be exactly 11 digits!",
                    "Invalid Contact Number",
                    JOptionPane.WARNING_MESSAGE);
                jsupcn.requestFocusInWindow();
            }
        }
    });
         jsuptable.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = jsuptable.getSelectedRow();
        if (selectedRow >= 0) {
            selectedSupplierId = Integer.parseInt(jsuptable.getValueAt(selectedRow, 0).toString());
            jsupid.setText(jsuptable.getValueAt(selectedRow, 0).toString()); // display only
            jsupname.setText(jsuptable.getValueAt(selectedRow, 1).toString());
            jsupcp.setText(jsuptable.getValueAt(selectedRow, 2).toString());
            jsupcn.setText(jsuptable.getValueAt(selectedRow, 3).toString());
            jsupemail.setText(jsuptable.getValueAt(selectedRow, 4).toString());
            jsupadd.setText(jsuptable.getValueAt(selectedRow, 5).toString());
        }
    }
         });
    }

    
    private void clearFields() {
    jsupname.setText("");
    jsupcp.setText("");
    jsupcn.setText("");
    jsupemail.setText("");
    jsupadd.setText("");
    selectedSupplierId = -1;
   
}
    
    

    
private void loadUserTable() {
    Connection con = DatabaseConnection.dbConnection();
    DefaultTableModel dtm = (DefaultTableModel) jsuptable.getModel();
    dtm.setRowCount(0);

    try {
        ResultSet rs = con.prepareStatement("SELECT * FROM suppliers ORDER BY supplier_name ASC").executeQuery();
        while (rs.next()) {
            Object[] obj = {
                rs.getInt("supplier_id"),
                rs.getString("supplier_name"),
                rs.getString("contact_person"),
                rs.getString("contact_number"),
                rs.getString("email"),
                rs.getString("address"),
            };
            dtm.addRow(obj);
        }
    } catch (Exception ex) {
        System.out.println(ex);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jsuptable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jsupsearchchat = new javax.swing.JTextField();
        jsupsearch = new javax.swing.JButton();
        jsupname = new javax.swing.JTextField();
        jsupcp = new javax.swing.JTextField();
        jsupcn = new javax.swing.JTextField();
        jsupemail = new javax.swing.JTextField();
        jsupadd = new javax.swing.JTextField();
        jsupid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jsupregister = new javax.swing.JButton();
        jsupdelete = new javax.swing.JButton();
        jsupupdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Swis721 BT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplies");

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rpand\\Documents\\GitHub\\Andulana_EDP\\src\\andulanarobert1\\images\\return.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23))
        );

        jsuptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Supplier ID", "Supplier Name", "Contact person", "Contact Number", "Email Address", "Address"
            }
        ));
        jScrollPane1.setViewportView(jsuptable);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Swis721 BT", 3, 18)); // NOI18N
        jLabel3.setText("Category Name");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Swis721 BT", 3, 18)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Swis721 BT", 3, 18)); // NOI18N
        jLabel5.setText("Supplier Name");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Swis721 BT", 3, 18)); // NOI18N
        jLabel6.setText("Contact Person");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Swis721 BT", 3, 18)); // NOI18N
        jLabel7.setText("Contact Number");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Swis721 BT", 3, 18)); // NOI18N
        jLabel8.setText("Email Address");

        jsupsearch.setText("Search");
        jsupsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupsearchActionPerformed(evt);
            }
        });

        jsupcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupcnActionPerformed(evt);
            }
        });

        jsupid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupidActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Swis721 BT", 3, 18)); // NOI18N
        jLabel9.setText("Supplier ID");

        jsupregister.setText("Register");
        jsupregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupregisterActionPerformed(evt);
            }
        });

        jsupdelete.setText("Delete");
        jsupdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupdeleteActionPerformed(evt);
            }
        });

        jsupupdate.setText("Update");
        jsupupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jsupregister, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jsupdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jsupupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jsupsearchchat, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jsupsearch))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jsupcp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jsupname, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jsupcn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsupemail, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jsupid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jsupadd, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 31, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(388, 388, 388)
                    .addComponent(jLabel3)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsupsearchchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsupsearch))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsupid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(jsupname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsupcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsupcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsupemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsupadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jsupregister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jsupdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsupupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(11, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(253, 253, 253)
                    .addComponent(jLabel3)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jsupsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupsearchActionPerformed
        // TODO add your handling code here:
        String search = jsupsearchchat.getText().trim();

    Connection con = DatabaseConnection.dbConnection();
    DefaultTableModel dtm = (DefaultTableModel) jsuptable.getModel();
    dtm.setRowCount(0); // clears table before showing results

    try {

        String sql = "SELECT * FROM suppliers WHERE supplier_id LIKE ? OR supplier_name LIKE ?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, "%" + search + "%");
        pst.setString(2, "%" + search + "%");

        ResultSet rs = pst.executeQuery();

        boolean found = false;

        while (rs.next()) {

            found = true;

            Object obj[] = {
                rs.getInt("supplier_id"),
                rs.getString("supplier_name"),
                rs.getString("contact_person"),
                rs.getString("contact_number"),
                rs.getString("email"),
                rs.getString("address")
            };

            dtm.addRow(obj);
        }

        if(!found){
            JOptionPane.showMessageDialog(null, "No matching Suppliers found.");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
    }
        
    }//GEN-LAST:event_jsupsearchActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
          Connection con = DatabaseConnection.dbConnection(); 
      ResultSet rs;
      DefaultTableModel dtm = (DefaultTableModel) jsuptable.getModel(); 
      dtm.setRowCount(0);
      try{
           PreparedStatement pst  = con.prepareStatement("SELECT * FROM suppliers ORDER BY supplier_name ASC");
           rs = pst.executeQuery();
           while(rs.next()){
               Object obj[] = {rs.getInt("supplier_id"), rs.getString("supplier_name"), rs.getString("contact_person"),rs.getString("contact_number"),
                   rs.getString("email"), rs.getString("address")};
               dtm.addRow(obj);
           }
               }catch (Exception ex){
                   System.out.println(ex);
               }
      
        
    }//GEN-LAST:event_formWindowActivated

    private void jsupregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupregisterActionPerformed
        // TODO add your handling code here:
         Connection con = DatabaseConnection.dbConnection();
    String supplier_name = jsupname.getText();
    String contact_person = jsupcp.getText();
    String contact_number = jsupcn.getText();
    String email = jsupemail.getText();
    String address = jsupadd.getText();

    if (supplier_name.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Supplier name is required.");
        return;
    }
    if (email.isEmpty() || !email.contains("@") || !email.contains(".")) {
    JOptionPane.showMessageDialog(null, "Please enter a valid email address (e.g. name@gmail.com, name@yahoo.com)");
    return;
    }
    if (contact_number.length() != 11) {
    JOptionPane.showMessageDialog(null, "Contact number must be exactly 11 digits.");
    return;

}

    try {
        PreparedStatement pst = con.prepareStatement(
            "INSERT INTO suppliers (supplier_name, contact_person, contact_number, email, address) VALUES (?, ?, ?, ?, ?)"
        );
        pst.setString(1, supplier_name);
        pst.setString(2, contact_person);
        pst.setString(3, contact_number);
        pst.setString(4, email);
        pst.setString(5, address);

        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Supplier added successfully!");
        clearFields();
        loadUserTable();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
    }
    }//GEN-LAST:event_jsupregisterActionPerformed

    private void jsupdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupdeleteActionPerformed
        // TODO add your handling code here:
         String supplier_id = jsupid.getText();

        if (supplier_id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a supplier to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this supplier?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection con = DatabaseConnection.dbConnection();
                String sql = "DELETE FROM suppliers WHERE supplier_id=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, supplier_id);

                int deleted = pst.executeUpdate();

                if (deleted > 0) {
                    JOptionPane.showMessageDialog(null, "supplier deleted successfully!");
                    clearFields();
                    loadUserTable();
                } else {
                    JOptionPane.showMessageDialog(null, "Delete failed. Please check the supplier ID.");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jsupdeleteActionPerformed

    private void jsupupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupupdateActionPerformed
        // TODO add your handling code here:
         int supplier_id = Integer.parseInt(jsupid.getText());
            String supplier_name = jsupname.getText();
            String contact_person = jsupcp.getText();
            String contact_number = jsupcn.getText();
            String email = jsupemail.getText();
            String address = jsupadd.getText();

    try {
        Connection con = DatabaseConnection.dbConnection();
        String sql = "UPDATE suppliers SET supplier_name=?, contact_person=?, contact_number=?, email=?, address=? WHERE supplier_id=?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, supplier_name);
        pst.setString(2, contact_person);
        pst.setString(3, contact_number);
        pst.setString(4, email);
        pst.setString(5, address);
        pst.setInt(6, supplier_id);

int updated = pst.executeUpdate();

        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "suppliers updated successfully!");
            loadUserTable();  // method to refresh the table
        } else {
            JOptionPane.showMessageDialog(this, "Update failed. Please check the suppliers ID.");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }//GEN-LAST:event_jsupupdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Return to Dashboard", "Are you sure?",JOptionPane.YES_NO_OPTION);
        if(confirm == YES_OPTION){
         Dashboard db = new  Dashboard();
        db.show();
        this.dispose();
        }else{
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jsupidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsupidActionPerformed

    private void jsupcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupcnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jsupcnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jsupadd;
    private javax.swing.JTextField jsupcn;
    private javax.swing.JTextField jsupcp;
    private javax.swing.JButton jsupdelete;
    private javax.swing.JTextField jsupemail;
    private javax.swing.JTextField jsupid;
    private javax.swing.JTextField jsupname;
    private javax.swing.JButton jsupregister;
    private javax.swing.JButton jsupsearch;
    private javax.swing.JTextField jsupsearchchat;
    private javax.swing.JTable jsuptable;
    private javax.swing.JButton jsupupdate;
    // End of variables declaration//GEN-END:variables
}
